# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{veneer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Neighman"]
  s.date = %q{2009-11-03}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{has.sox@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "datamapper_setup.rb",
     "lib/veneer.rb",
     "lib/veneer/adapters/activerecord.rb",
     "lib/veneer/adapters/activerecord/class_wrapper.rb",
     "lib/veneer/adapters/activerecord/instance_wrapper.rb",
     "lib/veneer/adapters/datamapper.rb",
     "lib/veneer/adapters/datamapper/class_wrapper.rb",
     "lib/veneer/adapters/datamapper/instance_wrapper.rb",
     "lib/veneer/base/class_wrapper.rb",
     "lib/veneer/base/conditional.rb",
     "lib/veneer/base/instance_wrapper.rb",
     "lib/veneer/core_ext/kernel.rb",
     "lib/veneer/errors.rb",
     "lib/veneer/proxy.rb",
     "test/macros/class_wrapper/create_macro.rb",
     "test/macros/class_wrapper/delete_macro.rb",
     "test/macros/class_wrapper/find_macro.rb",
     "test/macros/instance_wrapper/destroy_macro.rb",
     "test/macros/instance_wrapper/new_record_macro.rb",
     "test/macros/instance_wrapper/save_macro.rb",
     "test/macros/veneer_constants_interface.rb",
     "test/support/helpers.rb",
     "test/test_helper.rb",
     "test/veneer/adapters/active_record/active_record_setup.rb",
     "test/veneer/adapters/active_record/class_wrapper_test.rb",
     "test/veneer/adapters/active_record/instance_wrapper_test.rb",
     "test/veneer/adapters/datamapper/class_wrapper_test.rb",
     "test/veneer/adapters/datamapper/datamapper_setup.rb",
     "test/veneer/adapters/datamapper/instance_wrapper_test.rb",
     "test/veneer/base/conditonal_test.rb",
     "test/veneer/proxy_test.rb"
  ]
  s.homepage = %q{http://github.com/hassox/veneer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{veneer}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "test/macros/class_wrapper/create_macro.rb",
     "test/macros/class_wrapper/delete_macro.rb",
     "test/macros/class_wrapper/find_macro.rb",
     "test/macros/instance_wrapper/destroy_macro.rb",
     "test/macros/instance_wrapper/new_record_macro.rb",
     "test/macros/instance_wrapper/save_macro.rb",
     "test/macros/veneer_constants_interface.rb",
     "test/support/helpers.rb",
     "test/test_helper.rb",
     "test/veneer/adapters/active_record/active_record_setup.rb",
     "test/veneer/adapters/active_record/class_wrapper_test.rb",
     "test/veneer/adapters/active_record/instance_wrapper_test.rb",
     "test/veneer/adapters/datamapper/class_wrapper_test.rb",
     "test/veneer/adapters/datamapper/datamapper_setup.rb",
     "test/veneer/adapters/datamapper/instance_wrapper_test.rb",
     "test/veneer/base/conditonal_test.rb",
     "test/veneer/proxy_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

